services:
  bridge-bank:
    image: albianto/bridge-bank:latest
    container_name: bridge-bank
    restart: unless-stopped
    environment:
      - DOCKER_SOCKET=/var/run/docker.sock
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/compose:ro
    ports:
      - "3002:3000"
    environment:
      - TZ=Europe/Lisbon
